version: "3"

services:

  database:
    image: "postgres:latest"
    container_name: "sally-database"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
